config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :campaigns
  resources :characters, except: :index
  resources :users
  resources :games
  resources :organizations
  resources :runs, except: :index
  resources :sessions, except: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :sessions
  belongs_to :organization
  has_and_belongs_to_many :editors, class_name: "User",
                          join_table: :campaigns_editors,
                          association_foreign_key: :editor_id
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
  has_and_belongs_to_many :editors, class_name: "User",
                          join_table: :characters_editors,
                          association_foreign_key: :editor_id
  has_many :run_npcs
  has_many :run_players
  has_many :session_npcs
  has_many :session_players
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :runs
  has_and_belongs_to_many :editors, class_name: "User",
                          join_table: :games_editors,
                          association_foreign_key: :editor_id
  has_and_belongs_to_many :authors, class_name: "User",
                          join_table: :games_authors,
                          association_foreign_key: :author_id
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :game
  has_and_belongs_to_many :editors, class_name: "User",
                          join_table: :runs_editors,
                          association_foreign_key: :editor_id
  has_and_belongs_to_many :gms, class_name: "User",
                          join_table: :runs_gms,
                          association_foreign_key: :gm_id

  has_many :run_npcs
  has_many :run_players
  has_many :npcs, through: :run_npcs
  has_many :players, through: :run_players
end

app/models/run_npc.rb
class RunNpc < ApplicationRecord
  belongs_to :run
  belongs_to :npc, class_name: "User"
  belongs_to :character
end

app/models/run_player.rb
class RunPlayer < ApplicationRecord
  belongs_to :run
  belongs_to :player, class_name: "User"
  belongs_to :character
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :campaign
  has_and_belongs_to_many :gms, class_name: "User",
                          join_table: :sessions_gms,
                          association_foreign_key: :gm_id

  has_many :session_npcs
  has_many :session_players
  has_many :npcs, through: :session_npcs
  has_many :players, through: :session_players
end

app/models/session_npc.rb
class SessionNpc < ApplicationRecord
  belongs_to :session
  belongs_to :npc, class_name: "User"
  belongs_to :character
end

app/models/session_player.rb
class SessionPlayer < ApplicationRecord
  belongs_to :session
  belongs_to :player, class_name: "User"
  belongs_to :character
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:display_name])
    devise_parameter_sanitizer.permit(:edit, keys: [:display_name, :about_me])
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :set_campaign, only: [:show, :edit, :update]
  
  def index
    @campaign = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaigns_params)
    if @campaign.save!
      flash[:success] = "The campaign was successfully added."
      redirect_to @campaign and return
    else
      flash[:error] = "There was an error adding the campaign."
      redirect_to new_campaign_path and return
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update_attributes!(params[:id])
      flash[:success] = "The campaign was successfully updated."
      redirect_to @campaign
    else
      flash[:error] = "There was an error updating the campaign."
      redirect_to edit_campaign_path(@campaign) and return
    end
  end

  def destroy
    @campaign = Campaign.destroy(params[:id])
    flash[:success] = "The campaign was deleted."
    redirect_to campaigns_path and return
  end
  
  def set_campaign
		@campaign = Campaign.find(params[:id])
	end

  private

  def campaigns_params
    params.require(:campaign).permit(:name, :description, :organization)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(characters_params)
    if @character.save!
      flash[:success] = "Your character was created."
      redirect_to character_path(@character) and return
    else
      flash[:error] = "There was an error adding your character."
      redirect_to new_character_path and return
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update_attributes!(characters_params)
      flash[:success] = "Your character was updated."
      redirect_to character_path(@character) and return
    else
      flash[:error] = "There was an error updating your character."
      redirect_to edit_character_path(@character) and return
    end
  end

  def destroy
    @character = Character.destroy(params[:id])
    flash[:success] = "Your character was removed."
    redirect_to user_path(current_user) and return
  end

  private

  def characters_params
    params.require(:character).permit(:name, :game)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # get upcoming events
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    @session = Session.find(params[:id])
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(sessions_params)
    if @session.save!
      flash[:success] = "Your game session was added."
      redirect_to session_path(@session)
    else
      flash[:error] = "There was an error adding your game session."
      redirect_to new_session_path
    end
  end

  def edit
    @session = Session.find(params[:id])
  end

  def update
    @session = Session.find(params[:id])
    if @session.update_attributes!(sessions_params)
      flash[:success] = "Your game session was successfully updated."
      redirect_to session_path(@session)
    else
      flash[:error] = "There was an error updating your game session."
      redirect_to edit_session_path(@session)
    end
  end

  def destroy
    
  end

  private

  def sessions_params
    params.require(:session).permit(:title, :description, :website, :campaign_id, :start_datetime, :end_datetime, :location, :private)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    # I have nfc how the runs/campaigns/games/sessions thing works so I'll leave that to someone who designed the database to connect some dots here, ahaha.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/_form.html.erb
<div class="form-row">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form-row">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="form-row">
  <%= f.label :organization_id, "Organization "%>
  <%= f.collection_select :organization_id, Organization.all.order(:name), :id, :name, prompt: true %>
</div>

<div class="form-row">
  <%= f.submit "Save" %>
</div>

app/views/campaigns/edit.html.erb
<h2>Edit <%= @campaign.name %></h2>

<%= form_for @campaign, method: 'PATCH' do |f| %>
  <%= f.hidden_field :id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/campaigns/index.html.erb
<h2>List of Campaigns</h2>

<% if @campaigns.present? %>
  <ul>
    <% @campaigns.each do |campaign| %>
      <li><%= link_to @campaign.title, campaign_path(@campaign) %></li>
    <% end %>
  </ul>
<% end %>

app/views/campaigns/new.html.erb
<h2>New Campaign</h2>

<%= form_for @campaign, url: {action: 'create'} do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/campaigns/show.html.erb
<h2><%= @campaign.name %></h2>

<div class="desc">
  <%= @campaign.description %>
</div>

<dl>
  <% if @campaign.organization.present? %>
    <dt>Organized By:</dt>
    <dd><a href="<%= organization_path(@campaign.organization) %>"><%= @campaign.organization.name %></a></dd>
  <% end %>
</dl>

app/views/characters/_form.html.erb
<div class="form-row">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form-row">
  <%= f.label :game_id, "Played in Game" %>
  <%= f.collection_select :game_id, Game.all.order(:title), :id, :title, prompt: true %>
</div>

<div class="form-row">
  <%= f.submit "Save" %>
</div>

app/views/characters/edit.html.erb
<h2>Edit <%= @character.name %></h2>

<%= form_for @character, method: 'PATCH' do |f| %>
  <%= f.hidden_field :id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/characters/new.html.erb
<h2>New Character</h2>

<%= form_for @character, url: {action: 'create'} do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/characters/show.html.erb
<h2><%= @character.name %></h2>

<dl>
  <dt>Played in</dt>
  <dd><a href="<%= game_path(@character.game) %>"<%= @character.game.title %></a></dd>
</dl>

app/views/games/_form.html.erb
<div class="form-row">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="form-row">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="form-row">
  <%= f.label :website %>
  <%= f.url_field :website %>
</div>

<div class="form-row">
  <%= f.label :min_players, "Minimum Number of Players" %>
  <%= f.number_field :min_players, min: 1 %>
</div>

<div class="form-row">
  <%= f.label :max_players, "Maximum Number of Players" %>
  <%= f.number_field :max_players, min: 1 %>
</div>

<div class="form-row">
  <%= f.label :run_time, "Approximate Run Time" %>
  <%= f.text_field %>
</div>

<div class="form-row">
  <%= f.submit "Save" %>
</div>

app/views/games/edit.html.erb
<h2>Edit Game: <%= @game.title %></h2>

<%= form_for @game, method: 'PATCH' do |f| %>
  <%= f.hidden_field :id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/games/index.html.erb
<h2>List of Games</h2>

<% if @games.present? %>
  <ul>
    <% @games.each do |game| %>
      <li><%= link_to game.title, game_path(game) %></li>
    <% end %>
  </ul>
<% end %>

app/views/games/new.html.erb
<h2>New Game</h2>

<%= form_for @game, url: {action: 'create'} do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/games/show.html.erb
<h2>Game: <%= @game.title %></h2>

<h3>Description</h3>
<div class="description">
  <%= @game.description.html_safe %>
</div>

<dl>
  <dt>Website</dt>
  <dd><a href="<%= @game.website.html_safe %>"><%= @game.website.html_safe %></a></dd>
  <dt>Min. Number of Players</dt>
  <dd><%= @game.min_players %></dd>
  <dt>Max. Number of Players</dt>
  <dd><%= @game.max_players %></dd>
  <dt>Approx. Run Time</dt>
  <dd><%= @game.run_time %></dd>
</dl>

<% if @game.runs.present? %>
  <h3>Runs</h3>

  <ul>
    <% @game.runs.where(private: false).each do |run| %>
      <li><%= link_to "Run on #{run.start_datetime} at #{run.location}", run_path(run) %></li>
    <% end %>
  </ul>
<% end %>

app/views/home/index.html.erb
<h2>Upcoming Events</h2>

app/views/organizations/_form.html.erb
<div class="form-row">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form-row">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="form-row">
  <%= f.submit "Save" %>
</div>

app/views/organizations/edit.html.erb
<h2>Edit Organization: <%= @organization.name %></h2>

<%= form_for @organization, method: 'PATCH' do |f| %>
  <%= f.hidden_field :id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/organizations/index.html.erb
<h2>List of Organizations</h2>

<ul>
  <% @organizations.each do |organization| %>
    <li><%= link_to organization.name, organization_path(organization) %></li>
  <% end %>
</ul>

app/views/organizations/new.html.erb
<h2>New Organization</h2>

<%= form_for @organization, url: {action: 'create'} do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/organizations/show.html.erb
<h2>Organization: <%= @organization.name %></h2>

<div class="description">
  <%= @organization.description.html_safe %>
</div>

<% if @organization.campaigns.present? %>
  <h3>Campaigns</h3>

  <ul>
    <% @organization.campaigns.each do |campaign| %>
      <li><%= link_to campaign.name, campaign_path(campaign) %></li>
    <% end %>
  </ul>
<% end %>

app/views/runs/_form.html.erb
<div class="form-row">
  <%= f.label :game_id, "Run of Game" %>
  <%= f.collection_select :game_id, Game.all.order(:title), :id, :title, prompt: true %>
</div>

<div class="form-row">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="form-row">
  <%= f.label :website %>
  <%= f.url_field :website %>
</div>

<div class="form-row">
  <%= f.label :start_datetime, "Start Date & Time" %>
  <%= f.datetime_select :start_datetime %>
</div>

<div class="form-row">
  <%= f.label :end_datetime, "End Date & Time" %>
  <%= f.datetime_select :end_datetime %>
</div>

<div class="form-row">
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>

<div class="form-row">
  <%= f.label :private, "Make this run private?" %>
  <%= f.check_box :private %>
</div>

<div class="form-row">
  <%= f.submit, "Save" %>
</div>

app/views/runs/edit.html.erb
<h2>Edit Game Run for <%= @run.game.title %></h2>

<%= form_for @run, method: 'PATCH' do |f| %>
  <%= f.hidden_field :id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/runs/new.html.erb
<h2>New Game Run</h2>

<%= form_for @run, url: {action: 'create'} do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/runs/show.html.erb
<h2>Run of Game: <%= @run.game.title %></h2>

<h3>Description</h3>
<div class="description">
  <%= @run.description.html_safe %>
</div>

<dl>
  <dt>Website</dt>
  <dd><a href="<%= @run.website.html_safe %>"><%= @run.website.html_safe %></a></dd>
  <dt>Start Date &amp; Time</dt>
  <dd><%= @run.start_datetime %></dd>
  <dt>End Date &amp; Time</dt>
  <dd><%= @run.end_datetime %></dd>
  <dt>Location</dt>
  <dd><%= @run.location %></dd>
</dl>

app/views/users/show.html.erb
<h2><%= @user.display_name %>'s LARP Resume</h2>

<h3>Played</h3>
<ul>

</ul>

<h3>NPC Player</h3>
<ul>

</ul>

<h3>Ran</h3>
<ul>

</ul>

<h3>Authored</h3>
<ul>

</ul>